# WordPress-specific redirects
[[redirects]]
  from = "/wp-admin/*"
  to = "https://adamkoszary.co.uk/wp-admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/wp-content/*"
  to = "https://adamkoszary.co.uk/wp-content/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/wp-includes/*"
  to = "https://adamkoszary.co.uk/wp-includes/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/wp-json/*"
  to = "https://adamkoszary.co.uk/wp-json/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/wp-login.php"
  to = "https://adamkoszary.co.uk/wp-login.php"
  status = 200
  force = true

# Catch-all redirect for any WordPress requests not caught above
[[redirects]]
  from = "/wp-*"
  to = "https://adamkoszary.co.uk/:splat"
  status = 200
  force = true

# Serve your Astro frontend for all other requests
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200